name: "README.md Auto Update"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REPO_WORKSPACE: ${{ github.workspace }}

jobs:
  update-readme:
    if: github.event.head_commit.message != 'Update README.md'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Run script
      uses: ./.github/actions/update-readme
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update README.md
