name: README.md Self Update

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-readme:
    # Avoids workflow triggering in a loop
    if: github.event.head_commit.message != 'Update README.md'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        # Runs 'action.yml' from local action directory
      - name: Use local action
        uses: ./.github/actions/update-readme
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README.md
